name: patch-briosevka
on:
  push:
  workflow_dispatch:
  repository_dispatch:
jobs:
  patch-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: sudo apt-get install -y fontforge
      - name: Grab the script and its dependencies from the repo
        uses: snow-actions/sparse-checkout@v1.2.0
        with:
          repository: ryanoasis/nerd-fonts
          path: ./nerd-fonts
          patterns: |
            font-patcher
            src/glyphs
            src/archive-font-patcher-readme.md
            bin/scripts/archive-font-patcher.sh
            bin/scripts/name_parser
      - run: ./do-it.sh
      - run: tar -zcvf briosk-patched.tgz out/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: briosk-patched
          files: briosk-patched.tgz
